### ISSUE TITLE
Missing dependency: GTEventRecorderTestServer

### ISSUE THREAD

**Issue by tinchodias** [pharo-contributions/EventRecorder#7]
This Transcript message shows it:
~~~
'EREventRecorderDelegateTest>>setUp (GTEventRecorderTestServer is Undeclared)'
'EREventRecorderPutHandlerTest>>setUpServer (GTEventRecorderTestServer is Undeclared)'
~~~
Loaded in a Pharo 8 downloaded today using:
~~~
Metacello new 
  baseline: 'EventRecorder'; 
  repository: 'github://pharo-contributions/EventRecorder/';
  load.
~~~

**Comment by Ducasse** [comment]
Hi martin
Did you check the group?
Because there are separate packages
and indeed we should fix this. 
Thanks for the report. 
S

**Comment by tinchodias** [comment]
Hi. I just loaded the default group, but now I read the baseline: there is Core and All. By default, All was loaded... so I still have the same errors in tests. I can read the code a bit more later.
